blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or start a discussion
    url: https://github.com/<ORG>/<REPO>/discussions
    about: "General help or architectural debates belong here."
