services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Inside Docker, use the service name "mysql" (NOT localhost)
      - DATABASE_URL=mysql://root@mysql:3306/2invoiceme_local
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=2invoiceme_local
      # Allow root with NO password (dev-only)
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
