-- CreateTable
CREATE TABLE `invoicehistory` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `invoiceid` INTEGER NOT NULL,
    `action` ENUM('CREATE', 'SENT_FOR_CONFIRM', 'APPROVED', 'CANCEL', 'CHANGED_BY_CLIENT', 'CHANGED_BY_PROVIDER', 'CHANGE_APPROVED_BY_CLIENT', 'CHANGE_APPROVED_BY_PROVIDER') NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
