name: "👩‍💻 Development Task"
description: "New feature work, refactors, or code-cleanup tasks."
title: "[DEV] <brief description>"
labels: ["Developer Task"]


body:
  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "What are we trying to achieve? Link to story/epic if relevant."
      placeholder: "E.g., Implement OAuth2 login flow"
    validations:
      required: true
