name: "🛠️ Dev Ops Task"
description: "CI/CD, IaC, monitoring, scripting—anything infrastructure."
title: "[DEVOPS] <brief description>"
labels: ["DevOps Task"]

body:
  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "What are we trying to achieve? Link to story/epic if relevant."
      placeholder: "E.g., 'Automate the deployment of our application to production.'"
    validations:
      required: true
