name: "📚 Documentation Task"
description: "README updates, architecture diagrams, run-books."
title: "[DOCS] <brief description>"
labels: ["Documentation Task"]

body:
  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "What are we trying to achieve? Link to story/epic if relevant."
      placeholder: "E.g., Update the README to include the new feature."
    validations:
      required: true
