name: "🧪 QA / Test Task"
description: "Test-case authoring, exploratory testing, bug verification."
title: "[QA] <brief description>"
labels: ["QA Task"]

body:
  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "What is the goal of this task?"
      placeholder: "E.g., Verify that the 'Add to Cart' button is disabled when the quantity is 0."
    validations:
      required: true
