-- AlterTable
ALTER TABLE `invoicehistory` MODIFY `action` ENUM('CREATE', 'SENT_FOR_CONFIRM', 'APPROVED', 'COMPLETED', 'PAID', 'CANCEL', 'CHANGED_BY_CLIENT', 'CHANGED_BY_PROVIDER', 'CHANGE_APPROVED_BY_CLIENT', 'CHANGE_APPROVED_BY_PROVIDER') NOT NULL;
